// <auto-generated />
using System;
using KeysShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeysShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260103135651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KeysShop.Models.BuyHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Gameid_игры")
                        .HasColumnType("int");

                    b.Property<int>("KeyId")
                        .HasColumnType("int")
                        .HasColumnName("id_ключ");

                    b.Property<DateTime?>("PurchaseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("время_покупки");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_пользователь");

                    b.HasKey("id");

                    b.HasIndex("Gameid_игры");

                    b.HasIndex("KeyId");

                    b.HasIndex("PurchaseTime");

                    b.HasIndex("UserId");

                    b.ToTable("Buy_History");
                });

            modelBuilder.Entity("KeysShop.Models.Developer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("разработчик")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("разработчик");

                    b.HasKey("id");

                    b.ToTable("Developer");
                });

            modelBuilder.Entity("KeysShop.Models.Favorite", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_пользователя");

                    b.HasKey("id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("KeysShop.Models.Game", b =>
                {
                    b.Property<int>("id_игры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_игры"));

                    b.Property<int?>("id_разработчика")
                        .HasColumnType("int")
                        .HasColumnName("id_разработчика");

                    b.Property<string>("год_выпуска")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("год_выпуска");

                    b.Property<string>("изображение")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("изображение");

                    b.Property<string>("название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("название");

                    b.Property<string>("описание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("описание");

                    b.Property<decimal?>("цена")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("цена");

                    b.HasKey("id_игры");

                    b.HasIndex("id_разработчика");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("KeysShop.Models.GameGenre", b =>
                {
                    b.Property<int>("id_игры")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<int>("id_жанра")
                        .HasColumnType("int")
                        .HasColumnName("id_жанра");

                    b.Property<int>("id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.HasKey("id_игры", "id_жанра");

                    b.HasIndex("id_жанра");

                    b.ToTable("Games_Genre");
                });

            modelBuilder.Entity("KeysShop.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("жанр")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("жанр");

                    b.HasKey("id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("KeysShop.Models.Key", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("id_игры")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<string>("ключ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ключ");

                    b.Property<bool?>("продан")
                        .HasColumnType("bit")
                        .HasColumnName("продан");

                    b.HasKey("id");

                    b.HasIndex("id_игры");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("KeysShop.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("имя");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("пароль");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("User")
                        .HasColumnName("роль");

                    b.HasKey("id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KeysShop.Models.BuyHistory", b =>
                {
                    b.HasOne("KeysShop.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("Gameid_игры")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeysShop.Models.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeysShop.Models.User", "User")
                        .WithMany("BuyHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Key");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeysShop.Models.Favorite", b =>
                {
                    b.HasOne("KeysShop.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeysShop.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KeysShop.Models.Game", b =>
                {
                    b.HasOne("KeysShop.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("id_разработчика");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("KeysShop.Models.GameGenre", b =>
                {
                    b.HasOne("KeysShop.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("id_жанра")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KeysShop.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("id_игры")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("KeysShop.Models.Key", b =>
                {
                    b.HasOne("KeysShop.Models.Game", "Game")
                        .WithMany("Keys")
                        .HasForeignKey("id_игры");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("KeysShop.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("KeysShop.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("Keys");
                });

            modelBuilder.Entity("KeysShop.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("KeysShop.Models.User", b =>
                {
                    b.Navigation("BuyHistory");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
